var var_variant : Variant
var var_aabb : AABB
var var_array : Array
var var_basis : Basis
var var_bool : bool
var var_callable : Callable
var var_color : Color
var var_dictionary : Dictionary
var var_float : float
var var_int : int
var var_nodepath : NodePath
var var_object : Object
var var_packedbytearray : PackedByteArray
var var_packedcolorarray : PackedColorArray
var var_packedfloat32array : PackedFloat32Array
var var_packedfloat64array : PackedFloat64Array
var var_packedint32array : PackedInt32Array
var var_packedint64array : PackedInt64Array
var var_packedstringarray : PackedStringArray
var var_packedvector2array : PackedVector2Array
var var_packedvector3array : PackedVector3Array
var var_plane : Plane
var var_projection : Projection
var var_quaternion : Quaternion
var var_rect2 : Rect2
var var_rect2i : Rect2i
var var_rid : RID
var var_signal : Signal
var var_string : String
var var_stringname : StringName
var var_transform2d : Transform2D
var var_transform3d : Transform3D
var var_vector2 : Vector2
var var_vector2i : Vector2i
var var_vector3 : Vector3
var var_vector3i : Vector3i
var var_vector4 : Vector4
var var_vector4i : Vector4i