name: Publish to Nuget
on:
  release:
    types:
      - published
env:
  Version: ${{ github.event.release.tag_name }}
  PackageFile: {{cookiecutter.name}}.${{ github.event.release.tag_name }}.nupkg
  
jobs:
  create_nuget:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3

    - name: Pack
      run: dotnet pack --configuration Release -p:PackageVersion=${{ env.Version }} --output .
    
    - name: Publish NuGet package
      run: dotnet nuget push ${{ env.PackageFile }} --api-key "${{ secrets.NUGET_APIKEY }}" --source https://api.nuget.org/v3/index.json --skip-duplicate
