name: Test

on:
  push:
    branches: ['main']
    paths: ['GDBridge.Generator/**']
  pull_request:
    branches: [ "*" ]
    paths: ['GDBridge.Generator/**']

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      
    - name: Test
      run: dotnet test --verbosity normal
